### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by supriyasinhaa** [DSC-SIST/D-Bug#16]
## 📚 Documentation

Remove the repetitions in the Code of Conduct. The sub-headings which are in repetitions are:
- Our Pledge
- Our Standards
- Our Responsibilities
- Scope
- Enforcement
Except Enforcement all the content remains the same. 

### Have you read the Contributing Guidelines on Pull Requests?

Yes.

**Comment by AvinashMahanthi** [comment]
I had updated the Code of Conduct file, once you reviewed it, plz merge @supriyasinhaa

**Comment by supriyasinhaa** [comment]
Yes. Reviewed.
